/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.embarcados.comunicacaoserial;

import javax.swing.JTextField;

/**
 *
 * @author Tom
 */
public class JFInterface extends javax.swing.JFrame {

    Arduino conn = new Arduino();

    /**
     * Creates new form JFInterface
     */
    public JFInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBLedOn = new javax.swing.JButton();
        jBLedOff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBDesligaMotor = new javax.swing.JButton();
        jBNivel1 = new javax.swing.JButton();
        jBNivel2 = new javax.swing.JButton();
        jBNivel3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBTemperatura = new javax.swing.JButton();
        jTemp = new javax.swing.JTextField();
        jBClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBLedOn.setText("Ligar");
        jBLedOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLedOnMouseClicked(evt);
            }
        });
        jBLedOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLedOnActionPerformed(evt);
            }
        });

        jBLedOff.setText("Desligar");
        jBLedOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLedOffMouseClicked(evt);
            }
        });
        jBLedOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLedOffActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("LED:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Motor:");

        jBDesligaMotor.setText("Desligado");
        jBDesligaMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBDesligaMotorMouseClicked(evt);
            }
        });
        jBDesligaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesligaMotorActionPerformed(evt);
            }
        });

        jBNivel1.setText("Nível 1");
        jBNivel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBNivel1MouseClicked(evt);
            }
        });

        jBNivel2.setText("Nível 2");
        jBNivel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBNivel2MouseClicked(evt);
            }
        });

        jBNivel3.setText("Nível 3");
        jBNivel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBNivel3MouseClicked(evt);
            }
        });
        jBNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNivel3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Temperatura:");

        jBTemperatura.setText("Ler");
        jBTemperatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTemperaturaMouseClicked(evt);
            }
        });
        jBTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTemperaturaActionPerformed(evt);
            }
        });

        jTemp.setEditable(false);
        jTemp.setBackground(new java.awt.Color(204, 204, 204));
        jTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTempActionPerformed(evt);
            }
        });

        jBClose.setText("Sair");
        jBClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBLedOn)
                        .addGap(18, 18, 18)
                        .addComponent(jBLedOff))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBDesligaMotor)
                                .addGap(18, 18, 18)
                                .addComponent(jBNivel1)
                                .addGap(18, 18, 18)
                                .addComponent(jBNivel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBTemperatura)
                                .addGap(18, 18, 18)
                                .addComponent(jTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBNivel3)
                            .addComponent(jBClose))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLedOn)
                    .addComponent(jBLedOff))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDesligaMotor)
                    .addComponent(jBNivel1)
                    .addComponent(jBNivel2)
                    .addComponent(jBNivel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTemperatura)
                            .addComponent(jTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBClose)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLedOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLedOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLedOnActionPerformed

    private void jBLedOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLedOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLedOffActionPerformed

    private void jBTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTemperaturaActionPerformed

    private void jTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTempActionPerformed

    private void jBLedOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLedOnMouseClicked
        conn.comunicacaoArduino(jBLedOn);
    }//GEN-LAST:event_jBLedOnMouseClicked

    private void jBLedOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLedOffMouseClicked
        conn.comunicacaoArduino(jBLedOff);
    }//GEN-LAST:event_jBLedOffMouseClicked

    private void jBDesligaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesligaMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDesligaMotorActionPerformed

    private void jBNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNivel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNivel3ActionPerformed

    private void jBDesligaMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDesligaMotorMouseClicked
        conn.comunicacaoArduino(jBDesligaMotor);
    }//GEN-LAST:event_jBDesligaMotorMouseClicked

    private void jBNivel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNivel1MouseClicked
        conn.comunicacaoArduino(jBNivel1);
    }//GEN-LAST:event_jBNivel1MouseClicked

    private void jBNivel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNivel2MouseClicked
        conn.comunicacaoArduino(jBNivel2);
    }//GEN-LAST:event_jBNivel2MouseClicked

    private void jBNivel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNivel3MouseClicked
        conn.comunicacaoArduino(jBNivel3);
    }//GEN-LAST:event_jBNivel3MouseClicked

    private void jBTemperaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTemperaturaMouseClicked
        conn.comunicacaoArduino(jBTemperatura);
        jTemp.setText(conn.getTempLida());
    }//GEN-LAST:event_jBTemperaturaMouseClicked

    private void jBCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCloseMouseClicked
        conn.comunicacaoArduino(jBClose);
        System.exit(0);
    }//GEN-LAST:event_jBCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBDesligaMotor;
    private javax.swing.JButton jBLedOff;
    private javax.swing.JButton jBLedOn;
    private javax.swing.JButton jBNivel1;
    private javax.swing.JButton jBNivel2;
    private javax.swing.JButton jBNivel3;
    private javax.swing.JButton jBTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTemp;
    // End of variables declaration//GEN-END:variables

}
